#!/usr/bin/env python3
"""Generate Metal effects from the checked-in SDL3 GPU SPIR-V shaders.

Requires Khronos SPIRV-Cross (generated with commit
aa217aeb6c9f0ace7a0ab233b28807edf45eb165). The game needs no translator at runtime.
"""

import argparse
from pathlib import Path
import re
import subprocess
import tempfile


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spirv-cross", default="spirv-cross")
    parser.add_argument("--check", action="store_true", help="verify generated headers")
    args = parser.parse_args()
    shader_dir = Path(__file__).resolve().parents[1] / "Engine/Graphics/SDL3GPUShaders"
    with tempfile.TemporaryDirectory() as temporary:
        for header in sorted(shader_dir.glob("*.frag.spv.h")):
            if header.name == "texture_rgba.frag.spv.h":
                continue  # SDL's fixed shader already provides all native formats.
            source = header.read_text()
            symbol = re.search(r"unsigned char (\w+)_spv\[\]", source).group(1)
            spirv = Path(temporary) / "shader.spv"
            spirv.write_bytes(bytes(int(word, 16) for word in re.findall(r"0x([0-9a-fA-F]{2})", source)))
            # Keep the engine's texture slots even when SPIR-V lists resources
            # in a different order (notably the breakup effect).
            result = subprocess.run([args.spirv_cross, str(spirv), "--msl", "--msl-decoration-binding"],
                                    capture_output=True, text=True, check=True)
            generated = ("// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.\n"
                         f'static const unsigned char {symbol}_msl[] = R"ONS_MSL(\n'
                         + result.stdout + ')ONS_MSL";\n')
            output = header.with_name(header.name.replace(".spv.h", ".msl.h"))
            if args.check:
                if not output.exists() or output.read_text() != generated:
                    raise SystemExit(f"Out-of-date Metal shader: {output}")
            else:
                output.write_text(generated)


if __name__ == "__main__":
    main()
