// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.
static const unsigned char alpha_outside_textures_frag_msl[] = R"ONS_MSL(
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct main0_out
{
    float4 outColor [[color(0)]];
};

struct main0_in
{
    float2 texCoord [[user(locn1)]];
};

static inline __attribute__((always_inline))
float insideBox(thread const float2& v, thread const float2& bottomLeft, thread const float2& topRight)
{
    float2 s = step(bottomLeft, v) - step(topRight, v);
    return s.x * s.y;
}

fragment main0_out main0(main0_in in [[stage_in]], texture2d<float> tex [[texture(0)]], sampler texSmplr [[sampler(0)]])
{
    main0_out out = {};
    float4 img = tex.sample(texSmplr, in.texCoord);
    float2 param = in.texCoord;
    float2 param_1 = float2(0.0);
    float2 param_2 = float2(1.0);
    out.outColor = img * insideBox(param, param_1, param_2);
    return out;
}

)ONS_MSL";
