// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.
static const unsigned char blend_by_mask_frag_msl[] = R"ONS_MSL(
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct BlendByMaskUniforms
{
    int mask_value;
    char _m1_pad[12];
    int constant_mask;
    char _m2_pad[12];
    int crossfade;
};

struct main0_out
{
    float4 outColor [[color(0)]];
};

struct main0_in
{
    float2 inTexCoord [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]], constant BlendByMaskUniforms& uniforms [[buffer(0)]], texture2d<float> tex [[texture(0)]], texture2d<float> tex1 [[texture(1)]], texture2d<float> tex2 [[texture(2)]], sampler texSmplr [[sampler(0)]], sampler tex1Smplr [[sampler(1)]], sampler tex2Smplr [[sampler(2)]])
{
    main0_out out = {};
    float4 img1 = tex.sample(texSmplr, in.inTexCoord);
    float4 img2 = tex1.sample(tex1Smplr, in.inTexCoord);
    float4 _37;
    if (uniforms.constant_mask != 0)
    {
        _37 = float4(0.0);
    }
    else
    {
        _37 = tex2.sample(tex2Smplr, in.inTexCoord);
    }
    float4 mask = _37;
    if (uniforms.crossfade != 0)
    {
        float left = fast::clamp(((256.0 + (mask.x * 256.0)) - float(uniforms.mask_value)) / 256.0, 0.0, 1.0);
        out.outColor = fast::clamp((img1 * left) + (img2 * (1.0 - left)), float4(0.0), float4(1.0));
    }
    else
    {
        out.outColor = select(img2, img1, bool4((mask.x * 256.0) >= float(uniforms.mask_value)));
    }
    return out;
}

)ONS_MSL";
