// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.
static const unsigned char blur_v_frag_msl[] = R"ONS_MSL(
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct BlurUniforms
{
    float4 sigma;
    float4 blurSize;
};

struct main0_out
{
    float4 outColor [[color(0)]];
};

struct main0_in
{
    float2 inTexCoord [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]], constant BlurUniforms& uniforms [[buffer(0)]], texture2d<float> tex [[texture(0)]], sampler texSmplr [[sampler(0)]])
{
    main0_out out = {};
    float sigma = fast::max(uniforms.sigma.x, 9.9999997473787516355514526367188e-05);
    float blurSize = uniforms.blurSize.x;
    float3 incrementalGaussian;
    incrementalGaussian.x = 1.0 / (2.5066282749176025390625 * sigma);
    incrementalGaussian.y = exp((-0.5) / (sigma * sigma));
    incrementalGaussian.z = incrementalGaussian.y * incrementalGaussian.y;
    float4 avgValue = tex.sample(texSmplr, in.inTexCoord) * incrementalGaussian.x;
    float coefficientSum = incrementalGaussian.x;
    float3 _68 = incrementalGaussian;
    float3 _70 = incrementalGaussian;
    float2 _72 = _70.xy * _68.yz;
    incrementalGaussian.x = _72.x;
    incrementalGaussian.y = _72.y;
    for (float i = 1.0; i <= 4.0; i += 1.0)
    {
        float2 delta = float2(0.0, i * blurSize);
        avgValue += (tex.sample(texSmplr, (in.inTexCoord - delta)) * incrementalGaussian.x);
        avgValue += (tex.sample(texSmplr, (in.inTexCoord + delta)) * incrementalGaussian.x);
        coefficientSum += (2.0 * incrementalGaussian.x);
        float3 _120 = incrementalGaussian;
        float3 _122 = incrementalGaussian;
        float2 _124 = _122.xy * _120.yz;
        incrementalGaussian.x = _124.x;
        incrementalGaussian.y = _124.y;
    }
    out.outColor = avgValue / float4(coefficientSum);
    return out;
}

)ONS_MSL";
