// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.
static const unsigned char breakup_frag_msl[] = R"ONS_MSL(
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

// Implementation of the GLSL mod() function, which is slightly different than Metal fmod()
template<typename Tx, typename Ty>
inline Tx mod(Tx x, Ty y)
{
    return x - y * floor(x / y);
}

struct BreakupUniforms
{
    float tilesX;
    char _m1_pad[12];
    float tilesY;
    char _m2_pad[12];
    int breakupCellforms;
};

struct main0_out
{
    float4 outColor [[color(0)]];
};

struct main0_in
{
    float2 inTexCoord [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]], constant BreakupUniforms& uniforms [[buffer(0)]], texture2d<float> tex [[texture(0)]], texture2d<float> tex1 [[texture(1)]], texture2d<float> tex2 [[texture(2)]], sampler texSmplr [[sampler(0)]], sampler tex1Smplr [[sampler(1)]], sampler tex2Smplr [[sampler(2)]])
{
    main0_out out = {};
    float tilesX = fast::max(uniforms.tilesX, 1.0);
    float tilesY = fast::max(uniforms.tilesY, 1.0);
    int breakupCellforms = max(uniforms.breakupCellforms, 1);
    float belongsToTileX = floor(in.inTexCoord.x * tilesX) / tilesX;
    float belongsToTileY = floor(in.inTexCoord.y * tilesY) / tilesY;
    float gridReportedRadius = tex2.sample(tex2Smplr, float2(belongsToTileX, belongsToTileY)).x;
    float4 source = tex.sample(texSmplr, in.inTexCoord);
    if (gridReportedRadius >= 1.0)
    {
        out.outColor = source;
    }
    else
    {
        int thisRadius = int(floor(gridReportedRadius * float(breakupCellforms)));
        float xPercentageThroughTile = mod(in.inTexCoord.x, 1.0 / tilesX) * tilesX;
        float yPercentageThroughTile = mod(in.inTexCoord.y, 1.0 / tilesY) * tilesY;
        float breakupCellformsInterval = 1.0 / float(breakupCellforms);
        float breakupCellformsStartX = float(thisRadius - 1) * breakupCellformsInterval;
        float x = breakupCellformsStartX + (breakupCellformsInterval * xPercentageThroughTile);
        float y = yPercentageThroughTile;
        out.outColor = source * tex1.sample(tex1Smplr, float2(x, y)).x;
    }
    return out;
}

)ONS_MSL";
