// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.
static const unsigned char colour_conversion_frag_msl[] = R"ONS_MSL(
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct ColourConversionUniforms
{
    int4 conversionType;
    int4 maskHeight;
};

struct main0_out
{
    float4 outColor [[color(0)]];
};

struct main0_in
{
    float2 inTexCoord [[user(locn1)]];
};

static inline __attribute__((always_inline))
float3 grabYUV(thread const float2& coord, constant ColourConversionUniforms& uniforms, texture2d<float> tex, sampler texSmplr, texture2d<float> tex1, sampler tex1Smplr, texture2d<float> tex2, sampler tex2Smplr)
{
    if (uniforms.conversionType.x == 1)
    {
        return float3(tex.sample(texSmplr, coord).x, tex1.sample(tex1Smplr, coord).x, tex2.sample(tex2Smplr, coord).x);
    }
    float2 uv = tex1.sample(tex1Smplr, coord).xy;
    return float3(tex.sample(texSmplr, coord).x, uv.x, uv.y);
}

static inline __attribute__((always_inline))
float3 YUVToRGB(thread const float3& yuv)
{
    float y = (yuv.x - 0.062745101749897003173828125) * 1.16437995433807373046875;
    float cb = yuv.y - 0.501960813999176025390625;
    float cr = yuv.z - 0.501960813999176025390625;
    float3 rgb;
    rgb.x = y + (cr * 1.79273998737335205078125);
    rgb.y = (y - (0.53290998935699462890625 * cr)) - (0.21324999630451202392578125 * cb);
    rgb.z = y + (cb * 2.112400054931640625);
    return rgb;
}

fragment main0_out main0(main0_in in [[stage_in]], constant ColourConversionUniforms& uniforms [[buffer(0)]], texture2d<float> tex [[texture(0)]], texture2d<float> tex1 [[texture(1)]], texture2d<float> tex2 [[texture(2)]], sampler texSmplr [[sampler(0)]], sampler tex1Smplr [[sampler(1)]], sampler tex2Smplr [[sampler(2)]])
{
    main0_out out = {};
    bool _119 = uniforms.maskHeight.x != 0;
    bool _129;
    if (_119)
    {
        _129 = in.inTexCoord.y > 0.5;
    }
    else
    {
        _129 = _119;
    }
    if (_129)
    {
        out.outColor = float4(0.0);
        return out;
    }
    float2 param = in.inTexCoord;
    float3 param_1 = grabYUV(param, uniforms, tex, texSmplr, tex1, tex1Smplr, tex2, tex2Smplr);
    float4 rgba = float4(YUVToRGB(param_1), 1.0);
    if (uniforms.maskHeight.x > 0)
    {
        float2 param_2 = in.inTexCoord + float2(0.0, 0.5);
        float3 param_3 = grabYUV(param_2, uniforms, tex, texSmplr, tex1, tex1Smplr, tex2, tex2Smplr);
        rgba.w = YUVToRGB(param_3).x;
        float _165 = rgba.w;
        float4 _166 = rgba;
        float3 _168 = _166.xyz * _165;
        rgba.x = _168.x;
        rgba.y = _168.y;
        rgba.z = _168.z;
    }
    out.outColor = rgba;
    return out;
}

)ONS_MSL";
