// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.
static const unsigned char color_modification_frag_msl[] = R"ONS_MSL(
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct ColorModificationUniforms
{
    int4 modificationType;
    int4 multiplyAlpha;
    int4 blurFactor;
    int4 dimension;
    float4 darkenHue;
    float4 greyscaleHue;
    float4 replaceSrcColor;
    float4 replaceDstColor;
};

struct main0_out
{
    float4 outColor [[color(0)]];
};

struct main0_in
{
    float4 inColor [[user(locn0)]];
    float2 inTexCoord [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]], constant ColorModificationUniforms& uniforms [[buffer(0)]], texture2d<float> tex [[texture(0)]], sampler texSmplr [[sampler(0)]])
{
    main0_out out = {};
    float4 color = float4(0.0);
    int modificationType = uniforms.modificationType.x;
    if (modificationType == 0)
    {
        color = tex.sample(texSmplr, in.inTexCoord);
    }
    else
    {
        float grey;
        if (modificationType == 1)
        {
            color = tex.sample(texSmplr, in.inTexCoord);
            grey = dot(color.xyz, float3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
            if (color.w != 0.0)
            {
                color = float4(float3(1.2000000476837158203125, 1.0, 0.800000011920928955078125) * grey, color.w);
            }
        }
        else
        {
            float blurSize;
            if (modificationType == 2)
            {
                blurSize = 1.0 / float(uniforms.dimension.x);
                color += (tex.sample(texSmplr, float2(in.inTexCoord.x - (4.0 * blurSize), in.inTexCoord.y)) * 0.0500000007450580596923828125);
                color += (tex.sample(texSmplr, float2(in.inTexCoord.x - (3.0 * blurSize), in.inTexCoord.y)) * 0.0900000035762786865234375);
                color += (tex.sample(texSmplr, float2(in.inTexCoord.x - (2.0 * blurSize), in.inTexCoord.y)) * 0.119999997317790985107421875);
                color += (tex.sample(texSmplr, float2(in.inTexCoord.x - blurSize, in.inTexCoord.y)) * 0.1500000059604644775390625);
                color += (tex.sample(texSmplr, float2(in.inTexCoord.x, in.inTexCoord.y)) * 0.1599999964237213134765625);
                color += (tex.sample(texSmplr, float2(in.inTexCoord.x + blurSize, in.inTexCoord.y)) * 0.1500000059604644775390625);
                color += (tex.sample(texSmplr, float2(in.inTexCoord.x + (2.0 * blurSize), in.inTexCoord.y)) * 0.119999997317790985107421875);
                color += (tex.sample(texSmplr, float2(in.inTexCoord.x + (3.0 * blurSize), in.inTexCoord.y)) * 0.0900000035762786865234375);
                color += (tex.sample(texSmplr, float2(in.inTexCoord.x + (4.0 * blurSize), in.inTexCoord.y)) * 0.0500000007450580596923828125);
            }
            else
            {
                if (modificationType == 3)
                {
                    blurSize = 1.0 / float(uniforms.dimension.x);
                    color += (tex.sample(texSmplr, float2(in.inTexCoord.x, in.inTexCoord.y - (4.0 * blurSize))) * 0.0500000007450580596923828125);
                    color += (tex.sample(texSmplr, float2(in.inTexCoord.x, in.inTexCoord.y - (3.0 * blurSize))) * 0.0900000035762786865234375);
                    color += (tex.sample(texSmplr, float2(in.inTexCoord.x, in.inTexCoord.y - (2.0 * blurSize))) * 0.119999997317790985107421875);
                    color += (tex.sample(texSmplr, float2(in.inTexCoord.x, in.inTexCoord.y - blurSize)) * 0.1500000059604644775390625);
                    color += (tex.sample(texSmplr, float2(in.inTexCoord.x, in.inTexCoord.y)) * 0.1599999964237213134765625);
                    color += (tex.sample(texSmplr, float2(in.inTexCoord.x, in.inTexCoord.y + blurSize)) * 0.1500000059604644775390625);
                    color += (tex.sample(texSmplr, float2(in.inTexCoord.x, in.inTexCoord.y + (2.0 * blurSize))) * 0.119999997317790985107421875);
                    color += (tex.sample(texSmplr, float2(in.inTexCoord.x, in.inTexCoord.y + (3.0 * blurSize))) * 0.0900000035762786865234375);
                    color += (tex.sample(texSmplr, float2(in.inTexCoord.x, in.inTexCoord.y + (4.0 * blurSize))) * 0.0500000007450580596923828125);
                }
                else
                {
                    if (modificationType == 4)
                    {
                        color = tex.sample(texSmplr, in.inTexCoord);
                        grey = dot(color.xyz, float3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));
                        if (color.w != 0.0)
                        {
                            color = float4(grey, grey, grey, color.w);
                        }
                    }
                    else
                    {
                        if (modificationType == 5)
                        {
                            color = tex.sample(texSmplr, in.inTexCoord);
                            if (color.w != 0.0)
                            {
                                color = float4(1.0 - color.x, 1.0 - color.y, 1.0 - color.z, color.w);
                            }
                        }
                        else
                        {
                            if (modificationType == 6)
                            {
                                color = tex.sample(texSmplr, in.inTexCoord);
                                if (color.w != 0.0)
                                {
                                    color = float4(color.x * uniforms.darkenHue.x, color.y * uniforms.darkenHue.y, color.z * uniforms.darkenHue.z, color.w);
                                }
                            }
                            else
                            {
                                if (modificationType == 7)
                                {
                                    color = tex.sample(texSmplr, in.inTexCoord);
                                    bool _426 = color.x == uniforms.replaceSrcColor.x;
                                    bool _434;
                                    if (_426)
                                    {
                                        _434 = color.y == uniforms.replaceSrcColor.y;
                                    }
                                    else
                                    {
                                        _434 = _426;
                                    }
                                    bool _442;
                                    if (_434)
                                    {
                                        _442 = color.z == uniforms.replaceSrcColor.z;
                                    }
                                    else
                                    {
                                        _442 = _434;
                                    }
                                    if (_442)
                                    {
                                        color.x = uniforms.replaceDstColor.x;
                                        color.y = uniforms.replaceDstColor.y;
                                        color.z = uniforms.replaceDstColor.z;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    bool _455 = modificationType == 0;
    bool _462;
    if (!_455)
    {
        _462 = uniforms.multiplyAlpha.x == 1;
    }
    else
    {
        _462 = _455;
    }
    if (_462)
    {
        color.x *= color.w;
        color.y *= color.w;
        color.z *= color.w;
    }
    out.outColor = color + (in.inColor * 0.0);
    return out;
}

)ONS_MSL";
