// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.
static const unsigned char crop_by_mask_frag_msl[] = R"ONS_MSL(
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct main0_out
{
    float4 outColor [[color(0)]];
};

struct main0_in
{
    float2 inTexCoord [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]], texture2d<float> tex [[texture(0)]], texture2d<float> tex1 [[texture(1)]], sampler texSmplr [[sampler(0)]], sampler tex1Smplr [[sampler(1)]])
{
    main0_out out = {};
    float4 img = tex.sample(texSmplr, in.inTexCoord);
    float x = in.inTexCoord.x;
    float y = in.inTexCoord.y;
    float _117 = ((((((((tex1.sample(tex1Smplr, float2(x - 0.001953125, y - 0.001953125)).x * 0.111111111938953399658203125) + (tex1.sample(tex1Smplr, float2(x, y - 0.001953125)).x * 0.111111111938953399658203125)) + (tex1.sample(tex1Smplr, float2(x + 0.001953125, y - 0.001953125)).x * 0.111111111938953399658203125)) + (tex1.sample(tex1Smplr, float2(x - 0.001953125, y)).x * 0.111111111938953399658203125)) + (tex1.sample(tex1Smplr, float2(x, y)).x * 0.111111111938953399658203125)) + (tex1.sample(tex1Smplr, float2(x + 0.001953125, y)).x * 0.111111111938953399658203125)) + (tex1.sample(tex1Smplr, float2(x - 0.001953125, y + 0.001953125)).x * 0.111111111938953399658203125)) + (tex1.sample(tex1Smplr, float2(x, y + 0.001953125)).x * 0.111111111938953399658203125)) + (tex1.sample(tex1Smplr, float2(x + 0.001953125, y + 0.001953125)).x * 0.111111111938953399658203125);
    float mask = _117;
    out.outColor = img * mask;
    return out;
}

)ONS_MSL";
