// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.
static const unsigned char effect_whirl_frag_msl[] = R"ONS_MSL(
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct EffectWhirlUniforms
{
    int effect_counter;
    char _m1_pad[12];
    int duration;
    char _m2_pad[12];
    int direction;
    char _m3_pad[12];
    float render_width;
    char _m4_pad[12];
    float render_height;
    char _m5_pad[12];
    float texture_width;
    char _m6_pad[12];
    float texture_height;
};

struct main0_out
{
    float4 outColor [[color(0)]];
};

struct main0_in
{
    float2 inTexCoord [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]], constant EffectWhirlUniforms& uniforms [[buffer(0)]], texture2d<float> tex [[texture(0)]], sampler texSmplr [[sampler(0)]])
{
    main0_out out = {};
    int duration = max(uniforms.duration, 1);
    float t = (float(uniforms.effect_counter) * 3.1415927410125732421875) / float(duration * 2);
    float rad_amp = sin(2.0 * t);
    float rad_base = 0.0;
    int d = -1;
    bool _43 = uniforms.direction == (-1);
    bool _50;
    if (!_43)
    {
        _50 = uniforms.direction == 1;
    }
    else
    {
        _50 = _43;
    }
    if (_50)
    {
        rad_base = 4.0 * t;
    }
    else
    {
        bool _60 = uniforms.direction == (-2);
        bool _67;
        if (!_60)
        {
            _67 = uniforms.direction == 2;
        }
        else
        {
            _67 = _60;
        }
        if (_67)
        {
            d = int(fast::clamp(float(d), -1.0, 1.0));
            float one_minus_cos = 1.0 - cos(t);
            rad_amp = 3.1415927410125732421875 * (sin(t) - one_minus_cos);
            rad_base = (6.283185482025146484375 * one_minus_cos) + rad_amp;
        }
    }
    float renderWidth = fast::max(uniforms.render_width, 1.0);
    float renderHeight = fast::max(uniforms.render_height, 1.0);
    float textureWidth = fast::max(uniforms.texture_width, 1.0);
    float textureHeight = fast::max(uniforms.texture_height, 1.0);
    float centre_x = renderWidth / 2.0;
    float centre_y = renderHeight / 2.0;
    float x = (in.inTexCoord.x * textureWidth) - centre_x;
    float y = (in.inTexCoord.y * textureHeight) - centre_y;
    float theta = float(d) * (rad_base + (rad_amp * sin(sqrt((x * x) + (y * y)) * 0.0490873865783214569091796875)));
    float i = fast::clamp(((x * cos(theta)) - (y * sin(theta))) + centre_x, 0.0, renderWidth - 1.0);
    float j = fast::clamp(((x * sin(theta)) + (y * cos(theta))) + centre_y, 0.0, renderHeight - 1.0);
    out.outColor = tex.sample(texSmplr, float2(i / textureWidth, j / textureHeight));
    return out;
}

)ONS_MSL";
