// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.
static const unsigned char effect_trvswave_frag_msl[] = R"ONS_MSL(
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct EffectTrvswaveUniforms
{
    int script_width;
    char _m1_pad[12];
    int script_height;
    char _m2_pad[12];
    int effect_counter;
    char _m3_pad[12];
    int duration;
};

struct main0_out
{
    float4 outColor [[color(0)]];
};

struct main0_in
{
    float2 inTexCoord [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]], constant EffectTrvswaveUniforms& uniforms [[buffer(0)]], texture2d<float> tex [[texture(0)]], sampler texSmplr [[sampler(0)]])
{
    main0_out out = {};
    int w = max(uniforms.script_width, 1);
    int h = max(uniforms.script_height, 1);
    int duration = max(uniforms.duration, 1);
    int effectCounter = uniforms.effect_counter;
    float ampl;
    float wvlen;
    if ((effectCounter * 2) < duration)
    {
        ampl = (18.0 * float(2 * effectCounter)) / float(duration);
        wvlen = 1.0 / (((0.013671875 * float(2 * effectCounter)) / float(duration)) + 0.001953125);
    }
    else
    {
        ampl = (18.0 * float(2 * (duration - effectCounter))) / float(duration);
        wvlen = 1.0 / (((0.013671875 * float(2 * (duration - effectCounter))) / float(duration)) + 0.001953125);
    }
    int i = int(in.inTexCoord.x * float(w));
    int j = int(in.inTexCoord.y * float(h));
    int ii = i + int(ampl * sin((6.283185482025146484375 * float(j)) / wvlen));
    ii = clamp(ii, 0, w - 1);
    out.outColor = tex.sample(texSmplr, float2(float(ii) / float(w), float(j) / float(h)));
    return out;
}

)ONS_MSL";
