// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.
static const unsigned char effect_warp_frag_msl[] = R"ONS_MSL(
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct EffectWarpUniforms
{
    float animationClock;
    char _m1_pad[12];
    float amplitude;
    char _m2_pad[12];
    float wavelength;
    char _m3_pad[12];
    float speed;
    char _m4_pad[12];
    float cx;
    char _m5_pad[12];
    float cy;
};

struct main0_out
{
    float4 outColor [[color(0)]];
};

struct main0_in
{
    float2 inTexCoord [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]], constant EffectWarpUniforms& uniforms [[buffer(0)]], texture2d<float> tex [[texture(0)]], sampler texSmplr [[sampler(0)]])
{
    main0_out out = {};
    float cx = fast::max(uniforms.cx, 9.9999997473787516355514526367188e-05);
    float cy = fast::max(uniforms.cy, 9.9999997473787516355514526367188e-05);
    float2 uv = in.inTexCoord;
    uv.x *= uniforms.cx;
    uv.y *= uniforms.cy;
    float x = (uv.x * 2.0) - 1.0;
    float y = (uv.y * 2.0) - 1.0;
    float r = sqrt((x * x) + (y * y));
    float phi = precise::atan2(y, x);
    float cyclePerSec = (uniforms.animationClock * 3.1415927410125732421875) * 2.0;
    float wavelength = fast::max(uniforms.wavelength, 9.9999997473787516355514526367188e-05);
    phi += (((uniforms.amplitude * 3.1415927410125732421875) / 1000.0) * sin(((cyclePerSec * uniforms.speed) * 0.0599999986588954925537109375) + ((6031858.0 * r) / (1080.0 * wavelength))));
    float2 newUv = uv;
    newUv.x = ((r * cos(phi)) + 1.0) / 2.0;
    newUv.y = ((r * sin(phi)) + 1.0) / 2.0;
    newUv.x = fast::clamp(newUv.x, 0.0, 1.0) / cx;
    newUv.y = fast::clamp(newUv.y, 0.0, 1.0) / cy;
    out.outColor = tex.sample(texSmplr, newUv);
    return out;
}

)ONS_MSL";
