// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.
static const unsigned char glyph_gradient_frag_msl[] = R"ONS_MSL(
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct GlyphGradientUniforms
{
    float4 color;
    int4 maxy;
    int4 faceAscender;
    int4 height;
};

struct main0_out
{
    float4 outColor [[color(0)]];
};

struct main0_in
{
    float4 inColor [[user(locn0)]];
    float2 inTexCoord [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]], constant GlyphGradientUniforms& uniforms [[buffer(0)]], texture2d<float> tex [[texture(0)]], sampler texSmplr [[sampler(0)]])
{
    main0_out out = {};
    float4 source = tex.sample(texSmplr, in.inTexCoord);
    float current_y = float(uniforms.height.x) * (1.0 - in.inTexCoord.y);
    float current_y_above_baseline = current_y - (float(uniforms.height.x) - float(uniforms.maxy.x));
    float percent_above_baseline = fast::max(0.0, current_y_above_baseline / float(uniforms.faceAscender.x));
    bool isWhite = all(float3(1.0) == uniforms.color.xyz);
    float lightening_factor = 0.5 * ((float(isWhite) * (percent_above_baseline - 0.60000002384185791015625)) + (float(!isWhite) * (0.64999997615814208984375 - percent_above_baseline)));
    out.outColor = float4(uniforms.color.x + lightening_factor, uniforms.color.y + lightening_factor, uniforms.color.z + lightening_factor, source.w);
    out.outColor = float4(out.outColor.x * out.outColor.w, out.outColor.y * out.outColor.w, out.outColor.z * out.outColor.w, out.outColor.w) + (in.inColor * 0.0);
    return out;
}

)ONS_MSL";
