// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.
static const unsigned char merge_alpha_frag_msl[] = R"ONS_MSL(
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct main0_out
{
    float4 outColor [[color(0)]];
};

struct main0_in
{
    float2 inTexCoord [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]], texture2d<float> tex [[texture(0)]], texture2d<float> tex1 [[texture(1)]], sampler texSmplr [[sampler(0)]], sampler tex1Smplr [[sampler(1)]])
{
    main0_out out = {};
    float4 color = tex.sample(texSmplr, in.inTexCoord);
    float4 colorSrc = tex1.sample(tex1Smplr, in.inTexCoord);
    color.w = colorSrc.x;
    color.x *= colorSrc.x;
    color.y *= colorSrc.x;
    color.z *= colorSrc.x;
    out.outColor = color;
    return out;
}

)ONS_MSL";
