// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.
static const unsigned char multiply_alpha_frag_msl[] = R"ONS_MSL(
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct main0_out
{
    float4 outColor [[color(0)]];
};

struct main0_in
{
    float2 inTexCoord [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]], texture2d<float> tex [[texture(0)]], sampler texSmplr [[sampler(0)]])
{
    main0_out out = {};
    float4 color = tex.sample(texSmplr, in.inTexCoord);
    color.x *= color.w;
    color.y *= color.w;
    color.z *= color.w;
    out.outColor = color;
    return out;
}

)ONS_MSL";
