// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.
static const unsigned char pixelate_frag_msl[] = R"ONS_MSL(
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PixelateUniforms
{
    int width;
    char _m1_pad[12];
    int height;
    char _m2_pad[12];
    int factor;
};

struct main0_out
{
    float4 outColor [[color(0)]];
};

struct main0_in
{
    float2 inTexCoord [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]], constant PixelateUniforms& uniforms [[buffer(0)]], texture2d<float> tex [[texture(0)]], sampler texSmplr [[sampler(0)]])
{
    main0_out out = {};
    float2 uv = in.inTexCoord;
    float px_w = 1.0 / float(max(uniforms.width, 1));
    float px_h = 1.0 / float(max(uniforms.height, 1));
    float cell_w = float(uniforms.factor + 1) * px_w;
    float cell_h = float(uniforms.factor + 1) * px_h;
    float2 coord = float2(cell_w * floor((uv.x / cell_w) + 0.5), cell_h * floor((uv.y / cell_h) + 0.5));
    out.outColor = float4(tex.sample(texSmplr, coord).xyz, 1.0);
    return out;
}

)ONS_MSL";
