// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.
static const unsigned char render_subtitles_frag_msl[] = R"ONS_MSL(
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct RenderSubtitlesUniforms
{
    int ntextures;
    float4 subDims[8];
    float4 subCoords[8];
    float4 subColors[8];
    float2 dstDims;
};

struct main0_out
{
    float4 outColor [[color(0)]];
};

struct main0_in
{
    float2 inTexCoord [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]], constant RenderSubtitlesUniforms& uniforms [[buffer(0)]], texture2d<float> subTex [[texture(0)]], sampler subTexSmplr [[sampler(0)]])
{
    main0_out out = {};
    float4 res = float4(0.0);
    float2 texCoordAbs = uniforms.dstDims * in.inTexCoord;
    int count = clamp(uniforms.ntextures, 0, 8);
    for (int i = 0; i < 8; i++)
    {
        if (i == count)
        {
            break;
        }
        float2 coords = uniforms.subCoords[i].xy;
        float2 dims = uniforms.subDims[i].xy;
        bool _69 = all(texCoordAbs >= coords);
        bool _78;
        if (_69)
        {
            _78 = all(texCoordAbs <= (coords + dims));
        }
        else
        {
            _78 = _69;
        }
        if (_78)
        {
            float alpha = subTex.sample(subTexSmplr, (((texCoordAbs - coords) + float2(0.0, float(i) * 256.0)) / float2(2048.0))).x * uniforms.subColors[i].w;
            float4 col = float4(uniforms.subColors[i].xyz * alpha, alpha);
            res = col + (res * (1.0 - col.w));
        }
    }
    out.outColor = res;
    return out;
}

)ONS_MSL";
