// Generated by Scripts/generate_sdl3_metal_shaders.py; do not edit.
static const unsigned char text_fade_frag_msl[] = R"ONS_MSL(
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct TextFadeUniforms
{
    int partial;
    char _m1_pad[12];
    int full;
    char _m2_pad[12];
    int width;
};

struct main0_out
{
    float4 outColor [[color(0)]];
};

struct main0_in
{
    float2 inTexCoord [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]], constant TextFadeUniforms& uniforms [[buffer(0)]], texture2d<float> tex [[texture(0)]], sampler texSmplr [[sampler(0)]])
{
    main0_out out = {};
    int current = int(in.inTexCoord.x * float(max(uniforms.width, 1)));
    float4 color = tex.sample(texSmplr, in.inTexCoord);
    if (current > uniforms.full)
    {
        if (current >= (uniforms.full + uniforms.partial))
        {
            color = float4(0.0);
        }
        else
        {
            if (uniforms.partial > 0)
            {
                color *= (1.0 - (float(current - uniforms.full) / float(uniforms.partial)));
            }
        }
    }
    out.outColor = color;
    return out;
}

)ONS_MSL";
